export const MUSCLES = ["Klatka", "Plecy", "Nogi", "Barki", "Biceps", "Triceps", "Brzuch"];
export type Lang = "pl" | "en";

export const TRANSLATIONS = {
  pl: {
    title: "Workout Designer",
    weight: "Waga (kg)",
    height: "Wzrost (cm)",
    days: "Dni w tygodniu",
    experience: "Poziom zaawansowania",
    goal: "Cel treningowy",
    equipment: "Dostępny sprzęt",
    duration: "Czas trwania",
    generate: "Generuj Plan",
    generating: "Tworzenie...",
    beginner: "Początkujący",
    intermediate: "Średniozaawansowany",
    advanced: "Zaawansowany",
    reduction: "Redukcja",
    hypertrophy: "Hipertrofia",
    strength: "Siła",
    gym: "Siłownia",
    dumbbells: "Hantle",
    bodyweight: "Masa ciała",
    bands: "Gumy",
    short: "Krótki (45 min)",
    medium: "Średni (60 min)",
    long: "Długi (90 min)",
    auto: "Automatyczny",
    replace: "Wymień",
    show: "Pokaż",
    hide: "Ukryj",
    instructions: "Instrukcja",
    no_instructions: "Brak szczegółowych instrukcji.",
    sets: "Serie",
    reps: "Powt.",
    rest: "Przerwa",
    nutrition: "Makroskładniki",
    calories: "Kalorie",
    protein: "Białko",
    fat: "Tłuszcz",
    carbs: "Węglowodany",
    day: "Dzień",
    workout_type: "Typ treningu",
    blocked_parts: "Zablokowane partie",
    blocked_desc: "Zaznacz partie, których nie możesz trenować.",
    personalization: "Twój Plan",
    workout_plan: "Harmonogram Treningowy",
    no_results: "Brak wyników dla podanych parametrów.",
    no_exercises_day: "Brak ćwiczeń.",
    nutrition_desc: "Wartości obliczone dla przeciętnej osoby dorosłej na podstawie Twoich danych.",
    approx_values: "Szacunkowe",
    include_warmup: "Dodaj rozgrzewkę",
    warmup_desc: "Osobna sekcja z ćwiczeniami mobilizacyjnymi przed treningiem.",
  },
  en: {
    title: "Workout Designer",
    weight: "Weight (kg)",
    height: "Height (cm)",
    days: "Days per week",
    experience: "Level",
    goal: "Goal",
    equipment: "Equipment",
    duration: "Duration",
    generate: "Generate Plan",
    generating: "Creating...",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    reduction: "Reduction",
    hypertrophy: "Hypertrophy",
    strength: "Strength",
    gym: "Gym",
    dumbbells: "Dumbbells",
    bodyweight: "Bodyweight",
    bands: "Bands",
    short: "Short (45 min)",
    medium: "Medium (60 min)",
    long: "Long (90 min)",
    auto: "Automatic",
    replace: "Replace",
    show: "Show",
    hide: "Hide",
    instructions: "Instructions",
    no_instructions: "No instructions available.",
    sets: "Sets",
    reps: "Reps",
    rest: "Rest",
    nutrition: "Nutrition",
    calories: "Calories",
    protein: "Protein",
    fat: "Fat",
    carbs: "Carbs",
    day: "Day",
    workout_type: "Workout Type",
    blocked_parts: "Blocked parts",
    blocked_desc: "Select parts you cannot train.",
    personalization: "Your Plan",
    workout_plan: "Workout Schedule",
    no_results: "No results for given parameters.",
    no_exercises_day: "No exercises.",
    nutrition_desc: "Calculated based on your input for an average adult.",
    approx_values: "Approximate",
    include_warmup: "Add warm-up",
    warmup_desc: "A separate section with mobility exercises before workout.",
  }
};

export const MUSCLE_GROUPS_MAP: Record<string, { pl: string, en: string }> = {
  "Klatka": { pl: "Klatka", en: "Chest" },
  "Plecy": { pl: "Plecy", en: "Back" },
  "Nogi": { pl: "Nogi", en: "Legs" },
  "Barki": { pl: "Barki", en: "Shoulders" },
  "Biceps": { pl: "Biceps", en: "Biceps" },
  "Triceps": { pl: "Triceps", en: "Triceps" },
  "Brzuch": { pl: "Brzuch", en: "Abs" },
  "Inne": { pl: "Inne", en: "Other" }
};

export const SUB_MUSCLE_MAP: Record<string, {pl: string, en: string}> = {
    "Góra klatki": { pl: "Góra klatki", en: "Upper Chest" },
    "Dół klatki": { pl: "Dół klatki", en: "Lower Chest" },
    "Środek klatki": { pl: "Środek klatki", en: "Middle Chest" },
    "Szerokość pleców": { pl: "Szerokość pleców", en: "Lats / Back Width" },
    "Grubość i górny grzbiet": { pl: "Grubość i górny grzbiet", en: "Upper Back & Thickness" },
    "Dół pleców": { pl: "Dół pleców", en: "Lower Back" },
    "Przód uda": { pl: "Przód uda", en: "Quads" },
    "Tył uda": { pl: "Tył uda", en: "Hamstrings" },
    "Pośladki": { pl: "Pośladki", en: "Glutes" },
    "Łydki - górna część": { pl: "Łydki - górna", en: "Upper Calves" },
    "Łydki - dolna część": { pl: "Łydki - dolna", en: "Lower Calves" },
    "Wewnętrzna strona ud": { pl: "Wewnętrzna strona ud", en: "Inner Thighs" },
    "Zewnętrzna strona ud": { pl: "Zewnętrzna strona ud", en: "Outer Thighs" },
    "Przedni akton": { pl: "Przód barku", en: "Front Delts" },
    "Boczny akton": { pl: "Bok barku", en: "Side Delts" },
    "Tylny akton": { pl: "Tył barku", en: "Rear Delts" },
    "Biceps - głowa długa": { pl: "Biceps (gł. długa)", en: "Biceps (Long Head)" },
    "Biceps - głowa krótka": { pl: "Biceps (gł. krótka)", en: "Biceps (Short Head)" },
    "Triceps - głowa długa": { pl: "Triceps (gł. długa)", en: "Triceps (Long Head)" },
    "Triceps - głowa boczna i przyśrodkowa": { pl: "Triceps (boczny/przyśr.)", en: "Triceps (Lateral/Medial)" },
    "Góra przedramienia": { pl: "Góra przedramienia", en: "Upper Forearms" },
    "Dół przedramienia": { pl: "Dół przedramienia", en: "Lower Forearms" },
    "Góra brzucha": { pl: "Góra brzucha", en: "Upper Abs" },
    "Dół brzucha": { pl: "Dół brzucha", en: "Lower Abs" },
    "Boki brzucha": { pl: "Boki brzucha", en: "Obliques" },
    "Głęboka stabilizacja": { pl: "Głęboka stabilizacja", en: "Core Stabilization" },
    "Biceps - ogólnie": { pl: "Biceps - ogólnie", en: "Biceps (General)" },
};


